server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: provider-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myself?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
mybatis-plus:
  type-aliases-package: com.spring.providerone.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  #eureka 配置
eureka:
  server:
  #关闭eureka自我保护
   enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
# 日志配置
logging:
  level:
    org.apache.ibatis: DEBUG


